### ISSUE TITLE
validatorのoptionsサポート

### ISSUE THREAD

**Issue by maisumakun** [izumin5210/rspec-validator_spec_helper#1]
カスタムバリデーターについても、

``` ruby
  validates :column, hoge: {foo: 'bar'}
```

というように引数指定をできますが、テスト時にこの引数を付与できないものでしょうか。

**Comment by izumin5210** [comment]
@maisumakun 確かにあると便利そう（というより必要になりそう）ですね
検討してみたいと思います:bow:
